baseurl = "https://toshikunblog.net/"
title = "Toshikun Dlife"
author = "@Toshikun"
copyright = "Copyright Â© 2020, @Toshikun"
canonifyurls = true
googleAnalytics = "UA-165344098-1"
paginate = 4
hasCJKLanguage = true
summaryLength = 40
theme = "hugo-blog-jeffprod"
useFaviconGenerator = true
disqusShortname = "https-toshikunblog-net"

[taxonomies]
    tag = "tags"
    category = "categories"
    archive = "archives"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = false
      xHTML = false
    [markup.goldmark.renderer]
        unsafe = true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 3
        ordered = true



pygmentsUseClasses = true
pygmentsCodefences = true

  
[params]
  twitterID = "@toshikun_photo"
  images = ["https://toshikunblog.net/img/images.jpg"]
  title = "Toshikun Dlife"
